### ISSUE TITLE
Luminescent Bog Early Game Dialog

### ISSUE THREAD

**Issue by MatthewMorisky** [AztecGameLab/LongTermGame5#150]
Player comes across Water god, introduces himself and gives dialogue that the Betrayers creatures have been invading his domain, and he is thankful for you getting rid of them and making the Luminescent Bog (Axolotl people from the Bog) safer, say next the player must find the fire god in the Nimbus Mountains and maybe opens a blocked gateway (programming will decide on this part)

**Comment by BrandonMRendon** [comment]
[Vindr.txt](https://github.com/AztecGameLab/LongTermGame5/files/6133159/Vindr.txt)

**Comment by RenDawn777** [comment]
[Istvel.txt](https://github.com/AztecGameLab/LongTermGame5/files/6133422/Istvel.txt)
