### ISSUE TITLE
4. fireball lock and key area

### ISSUE THREAD

**Issue by Kainkun** [AztecGameLab/LongTermGame5#210]
- [x] one way entrance
- [x] lock area
- [x] key area
- [x] exit
![image](https://user-images.githubusercontent.com/26811871/111844736-d135e280-88c0-11eb-90d1-9969f18d6c44.png)

**Comment by Exopl0x** [comment]
![FireballLockAndKey](https://user-images.githubusercontent.com/39041782/113451826-a1560700-93b7-11eb-85cb-49d42eda79f2.png)

Teaches player to Vertically fireball boost, Horizontally fireball boost, and diagonally fireball boost.

Orange star = Fireball ability location
Green star = Player spawn

Red Xs = Enemies
Red box = Lava flies

Light green dotted path = Pre-Fireball
Brown dotted path = Post-Fireball
Pink dotted path = Post-Fireball, failed jump into the lava fly pit

Orange Sparks = Fireball jump locations
