### ISSUE TITLE
6. freeze ability lock and key area

### ISSUE THREAD

**Issue by Kainkun** [AztecGameLab/LongTermGame5#212]
- [ ] one way entrance
- [ ] lock area
- [ ] key area
- [ ] exit
![image](https://user-images.githubusercontent.com/26811871/111845046-57522900-88c1-11eb-98d7-8c88d3a2463d.png)

**Comment by chmilk1** [comment]
![lava area](https://user-images.githubusercontent.com/5875553/114931237-d5372080-9dea-11eb-8153-1b1e5592c9fe.png)
