### ISSUE TITLE
8. Grapple lock and key area

### ISSUE THREAD

**Issue by Kainkun** [AztecGameLab/LongTermGame5#215]
- [x] one way entrance
- [x] lock area
- [x] key area
- [x] exit
![image](https://user-images.githubusercontent.com/26811871/111853517-92ac2200-88d8-11eb-9438-585e9f8c8bcc.png)

**Comment by alyg563** [comment]
![35F449ED-A698-4029-9782-A5D3B5CEB8AB](https://user-images.githubusercontent.com/43483413/112917286-2f2faa80-90b7-11eb-8bfc-9b0285119419.jpeg)

**Comment by alyg563** [comment]
![6741C383-6378-46FD-920A-241804AA1C9E](https://user-images.githubusercontent.com/43483413/114954193-db3ef880-9e0e-11eb-8ccf-f6220a161ae6.jpeg)
