### ISSUE TITLE
Water Hub

### ISSUE THREAD

**Issue by Kainkun** [AztecGameLab/LongTermGame5#230]

**Comment by alyg563** [comment]
![9D7FF542-4F40-4AB2-928D-C1D7D55E5F21](https://user-images.githubusercontent.com/43483413/112698153-4fa4fe00-8e46-11eb-866b-213e3cbb61a8.jpeg)

**Comment by alyg563** [comment]
![2DE325F5-F0B6-4722-8C50-0BBA52D72AD0](https://user-images.githubusercontent.com/43483413/112699122-6187a080-8e48-11eb-86c4-790f1a049c80.jpeg)
